### ISSUE TITLE
Code Release

### ISSUE THREAD

**Issue by yiboz2001** [xingy038/Dreamer-XL#1]
Hello, thank you for your outstanding work. When will the code be open-sourced?

**Comment by yiboz2001** [comment]
And, how much time would the optimization process of a single object take?

**Comment by xingy038** [comment]
Hi,
Thanks for your interest in our work. Since I am working on another project, I did not have enough time to clean up the code. I plan to release the code next month. It will take about 1.5 hours for one scene.

**Comment by ostjul** [comment]
Hey, I am really interested in the code as well? Any plans on releasing that code in the upcoming weeks?

**Comment by xingy038** [comment]
> Hey, I am really interested in the code as well? Any plans on releasing that code in the upcoming weeks?

Sorry for the late reply, I plan to release the code at the end of the month.

**Comment by xingy038** [comment]
code released.
