### ISSUE TITLE
sd xl question

### ISSUE THREAD

**Issue by Zhang-Jiahui** [xingy038/Dreamer-XL#2]
hello, you paper is great.
I want to ask some questions for help about using the sd xl. These questions may have nothing to do with your paper.

When I use the sd xl and SDS loss to generate a 3D object, it always failed and produce bad color just like this:
![image](https://github.com/user-attachments/assets/573ba470-568b-4bbf-bcc6-457c62d4b1a1)
I use the shap-e as the geometry prior. 
But, when I change the model to sd 2.1, the generation is ok.
It really puzzled me. I don't know what the trouble is. 
Could you provide some advice about generating 3D using sd xl and SDS?
I would appreciate if you could help. It will really help to me.
Thanks.

**Comment by xingy038** [comment]
I'm not sure what your baseline is. I think this problem arises from the SD gradient as mentioned in our paper.

**Comment by Zhang-Jiahui** [comment]
Thank you for your advice.
I also have some questions about the paper. Why the eauqtion(12) has two min() functions. And why the depth participated in the grad. I only used the rgb values from rendered image to calculate the SDS but not used depth. Of course, maybe we use different methods.
![image](https://github.com/user-attachments/assets/898ee3e0-5b8b-4aa7-a26a-31aa0988a3c2)

And one more thing, could you provide some codes about the core grad cliping method? Several lines of codes are also ok. I only need the grad clipping part codes. I can't wait to use sd xl to generate 3d.

Thank you for your help.

**Comment by xingy038** [comment]
> Thank you for your advice. I also have some questions about the paper. Why the eauqtion(12) has two min() functions. And why the depth participated in the grad. I only used the rgb values from rendered image to calculate the SDS but not used depth. Of course, maybe we use different methods. ![image](https://private-user-images.githubusercontent.com/62180041/352707623-898ee3e0-5b8b-4aa7-a26a-31aa0988a3c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0ODQzMzksIm5iZiI6MTcyNjQ4NDAzOSwicGF0aCI6Ii82MjE4MDA0MS8zNTI3MDc2MjMtODk4ZWUzZTAtNWI4Yi00YWE3LWEyNmEtMzFhYTA5ODhhM2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDEwNTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkM2M4OGViNmZmMWU3MDIyMGIxOTk2ODA4ZWNhNTE3MTU3OTE5MGM1MTEyNzFhNWI3ODQ2MWUzYTIwZDI4ZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9egcOnCvNDydKwXWF78qYDd_MhTx75-nQOlNdStBC34)
> 
> And one more thing, could you provide some codes about the core grad cliping method? Several lines of codes are also ok. I only need the grad clipping part codes. I can't wait to use sd xl to generate 3d.
> 
> Thank you for your help.

Sorry for the late reply, I plan to release the code at the end of the month. The arxiv's version has some problems.

**Comment by xingy038** [comment]
code released.
